# Generated by Django 5.2.8 on 2025-12-07 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tulio', '0003_alter_post_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add new boolean and timestamp fields to Post
        migrations.AddField(
            model_name='post',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        # Use a valid default for existing rows when adding a DateTimeField
        migrations.AddField(
            model_name='post',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='habilidade_oferecida',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, default='', null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        # Create Usuario model before wiring FK from Post to Usuario
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, default='', max_length=100)),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('foto_perfil', models.ImageField(blank=True, default='', null=True, upload_to='perfil/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade_proposta', models.CharField(blank=True, default='', max_length=150)),
                ('mensagem', models.TextField(blank=True, default='', max_length=500)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas', to='site_tulio.post')),
                ('usuario_interessado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_feitas', to='site_tulio.usuario')),
            ],
        ),
        # Add FK to Usuario as nullable first; we'll populate it from the existing autor field and then remove autor
        migrations.AddField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='site_tulio.usuario'),
        ),
        # Populate Usuario objects and copy post.autor -> post.usuario
        migrations.RunPython(
            code=(
                lambda apps, schema_editor: (
                    (lambda:
                        [
                            (lambda UserModel, UsuarioModel, PostModel: (
                                [
                                    UsuarioModel.objects.get_or_create(user_id=u.pk)
                                    for u in UserModel.objects.all()
                                ],
                                [
                                    (setattr(p, 'usuario_id', UsuarioModel.objects.get(user_id=p.autor_id).pk), p.save())
                                    for p in PostModel.objects.all() if getattr(p, 'autor_id', None) is not None
                                ]
                            ))(
                                apps.get_model(*settings.AUTH_USER_MODEL.split('.')),
                                apps.get_model('site_tulio', 'Usuario'),
                                apps.get_model('site_tulio', 'Post')
                            )
                        ][-1]
                    )()
                )
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        # Now make usuario non-nullable
        migrations.AlterField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='site_tulio.usuario'),
        ),
        # Finally remove the old autor field
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
    ]
