# Generated by Django 5.2.8 on 2025-12-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tulio', '0004_remove_post_autor_post_ativa_post_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='troca',
            name='video_proposto',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
